# Site settings
title: Justin Munn
email: design@justinwmunn.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; 2014&mdash;2016 all rights reserved. Designed &amp; built by Justin Munn. Powered by <a href="https://jekyllrb.com/">Jekyll</a>, type served by <a href="http://typekit.com/">Typekit</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justinwmunn.co" # the base hostname & protocol for your site
twitter_username: jwmunn
github_username:  jwmunn
bg: "#F7931E"
# Build settings
markdown: kramdown
